import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Image } from "expo-image";
import { router } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ProgressHeader, ProgressNav, ProgressState, percent } from "../components/progress-layout";
import { useStudentProgress } from "../src/hooks/useStudentProgress";

export default function ProgressOverview() {
  const { dashboard, loading, error, reload } = useStudentProgress();
  if (loading || error) return <View style={s.page}><ProgressHeader/><ProgressState loading={loading} error={error} onRetry={reload}/><ProgressNav/></View>;
  const global = percent(dashboard?.progress.global_progress_pct ?? dashboard?.overview.global_progress_pct);
  const acts = dashboard?.progress.activities ?? {};
  const count = (keys:string[]) => { for (const key of keys) if (acts[key]?.completed != null) return acts[key].completed; return null; };
  const xp = dashboard?.overview.xp ?? dashboard?.student.xp;
  const name = dashboard?.student.first_name || "élève";
  return <View style={s.page}><ScrollView contentContainerStyle={s.content} showsVerticalScrollIndicator={false}><ProgressHeader/>
    <View style={s.hero}><Image source={require("../assets/images/dashboard-student-bg.webp")} contentFit="cover" style={StyleSheet.absoluteFill}/><Image source={require("../assets/images/dashboard-student-character.svg")} contentFit="contain" style={s.student}/><View style={s.greeting}><Text style={s.hello}>Salut {name} ! 👋</Text><Text style={s.sub}>Continue tes efforts, tu es sur la bonne voie !</Text></View><Image source={require("../assets/images/dashboard-student-cameleon.svg")} contentFit="contain" style={s.cameleon}/></View>
    <View style={s.dark}><Text style={s.darkTitle}>Progression globale</Text><View style={s.progressRow}><View style={s.ring}><Text adjustsFontSizeToFit minimumFontScale={0.72} numberOfLines={1} style={[s.ringValue, { width: "100%", fontSize: 21, lineHeight: 25, textAlign: "center", textAlignVertical: "center", includeFontPadding: false }]}>{global}%</Text></View><View style={s.legend}><Legend color="#65C94A" label="Cours terminés" value={count(["course","courses","lesson","lessons"])}/><Legend color="#4A91F3" label="Quiz réussis" value={count(["quiz","quizzes"])}/><Legend color="#9C64E8" label="Exercices faits" value={count(["exercise","exercises"])}/><Legend color="#FF881B" label="Vidéos regardées" value={count(["video","videos"])}/></View></View></View>
    <View style={s.stats}><Metric icon="local-fire-department" label="Série actuelle" value="—"/><Metric icon="star" label="XP total" value={xp == null ? "—" : String(xp)}/><Metric icon="favorite" label="Vies restantes" value="—"/></View>
    <Text style={s.sectionTitle}>Explorer mes statistiques</Text><View style={s.links}><Link icon="view-list" color="#7136CD" title="Détail par matière" path="/progress-subjects"/><Link icon="track-changes" color="#139D39" title="Mes objectifs" path="/progress-goals"/><Link icon="emoji-events" color="#F2A000" title="Badges & récompenses" path="/progress-rewards"/></View>
    <View style={s.emptyChart}><Text style={s.chartTitle}>Évolution dans le temps</Text><MaterialIcons name="timeline" size={50} color="#B8C6D9"/><Text style={s.chartHint}>L’historique détaillé apparaîtra dès qu’il sera disponible dans ton tableau de bord.</Text></View>
  </ScrollView><ProgressNav/></View>;
}
function Legend({color,label,value}:{color:string;label:string;value:number|null}){return <View style={s.legendRow}><View style={[s.bullet,{backgroundColor:color}]}/><Text style={s.legendText}>{label}</Text><Text style={s.legendValue}>{value ?? "—"}</Text></View>}
function Metric({icon,label,value}:{icon:React.ComponentProps<typeof MaterialIcons>["name"];label:string;value:string}){return <View style={s.metric}><MaterialIcons name={icon} size={29} color={icon==="favorite"?"#EF3C3C":"#F2A700"}/><Text style={s.metricLabel}>{label}</Text><Text style={s.metricValue}>{value}</Text></View>}
function Link({icon,color,title,path}:{icon:React.ComponentProps<typeof MaterialIcons>["name"];color:string;title:string;path:"/progress-subjects"|"/progress-goals"|"/progress-rewards"}){return <Pressable onPress={()=>router.push(path)} style={s.link}><View style={[s.linkIcon,{backgroundColor:`${color}18`}]}><MaterialIcons name={icon} color={color} size={25}/></View><Text style={s.linkText}>{title}</Text><MaterialIcons name="chevron-right" color="#52709D" size={25}/></Pressable>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#F4F8FD"},content:{paddingBottom:22},hero:{height:210,overflow:"hidden"},student:{position:"absolute",left:-15,bottom:-40,width:180,height:220},cameleon:{position:"absolute",right:-12,bottom:-3,width:125,height:125},greeting:{position:"absolute",left:150,top:55,right:105},hello:{fontSize:22,fontWeight:"900",color:"#102352"},sub:{fontSize:13,lineHeight:20,color:"#233C6A",marginTop:8,fontWeight:"600"},dark:{marginHorizontal:14,marginTop:-4,backgroundColor:"#052A6B",borderRadius:24,padding:18},darkTitle:{color:"white",fontSize:20,fontWeight:"900"},progressRow:{flexDirection:"row",alignItems:"center",marginTop:16},ring:{width:118,height:118,borderRadius:59,borderWidth:18,borderColor:"#4EB943",alignItems:"center",justifyContent:"center"},ringValue:{color:"white",fontSize:27,fontWeight:"900"},legend:{flex:1,marginLeft:18,gap:10},legendRow:{flexDirection:"row",alignItems:"center"},bullet:{width:12,height:12,borderRadius:6},legendText:{flex:1,color:"#EAF1FF",fontSize:12,marginLeft:8},legendValue:{color:"white",fontWeight:"900"},stats:{flexDirection:"row",margin:14,backgroundColor:"white",borderRadius:22,paddingVertical:17,elevation:3},metric:{flex:1,alignItems:"center",borderRightColor:"#E5EAF2",borderRightWidth:1},metricLabel:{fontSize:10,color:"#485C80",marginTop:6,textAlign:"center"},metricValue:{fontSize:19,fontWeight:"900",color:"#0E2659",marginTop:4},sectionTitle:{fontSize:19,fontWeight:"900",color:"#102352",marginHorizontal:18,marginBottom:9},links:{marginHorizontal:14,backgroundColor:"white",borderRadius:22,overflow:"hidden",elevation:2},link:{height:68,flexDirection:"row",alignItems:"center",paddingHorizontal:14,borderBottomWidth:1,borderBottomColor:"#E8EDF4"},linkIcon:{width:42,height:42,borderRadius:13,alignItems:"center",justifyContent:"center"},linkText:{flex:1,marginLeft:12,fontWeight:"900",color:"#102352"},emptyChart:{margin:14,backgroundColor:"white",borderRadius:22,padding:20,alignItems:"center",gap:10},chartTitle:{alignSelf:"flex-start",fontSize:18,fontWeight:"900",color:"#102352"},chartHint:{textAlign:"center",color:"#68758B",lineHeight:19}});
