import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Image } from "expo-image";
import { ScrollView, StyleSheet, Text, View } from "react-native";
import { ProgressHeader, ProgressNav, ProgressState, percent } from "../components/progress-layout";
import { useStudentProgress } from "../src/hooks/useStudentProgress";
type Goal={title:string;description:string;current?:number;target?:number;progress:number};
function goalsFrom(data?:Record<string,unknown>):Goal[]{if(!data)return[];return Object.entries(data).flatMap(([key,value])=>{if(!value||typeof value!=="object")return[];const v=value as Record<string,unknown>;const current=Number(v.current??v.completed??v.value);const target=Number(v.target??v.total??v.goal);const direct=Number(v.progress_pct??v.progress_percent);return [{title:String(v.title??v.label??key.replaceAll("_"," ")),description:String(v.description??v.message??"Objectif synchronisé avec EKALAN"),current:Number.isFinite(current)?current:undefined,target:Number.isFinite(target)?target:undefined,progress:percent(Number.isFinite(direct)?direct:(Number.isFinite(current)&&Number.isFinite(target)&&target?current/target*100:0))}]})}
export default function ProgressGoals(){const {dashboard,loading,error,reload}=useStudentProgress();if(loading||error)return <View style={s.page}><ProgressHeader back/><ProgressState loading={loading} error={error} onRetry={reload}/><ProgressNav/></View>;const goals=goalsFrom(dashboard?.goals);return <View style={s.page}><ScrollView contentContainerStyle={s.content}><ProgressHeader back/><View style={s.hero}><View><Text style={s.heroTitle}>Mes objectifs</Text><Text style={s.heroText}>Fixe tes objectifs et atteins-les !</Text></View><MaterialIcons name="track-changes" color="#FFD042" size={84}/></View><View style={s.tabs}><Text>Quotidiens</Text><Text style={s.active}>Hebdomadaires</Text><Text>Mensuels</Text></View>{goals.length?goals.map((goal,index)=><View key={`${goal.title}-${index}`} style={s.card}><View style={[s.icon,{backgroundColor:["#27B7D7","#61B83B","#7437C9","#FF7413"][index%4]}]}><MaterialIcons name={["schedule","menu-book","track-changes","assignment-turned-in"][index%4] as React.ComponentProps<typeof MaterialIcons>["name"]} size={26} color="white"/></View><View style={s.copy}><Text style={s.title}>{goal.title}</Text><Text style={s.description}>{goal.description}</Text><View style={s.track}><View style={[s.fill,{width:`${goal.progress}%`}]}/></View>{goal.current!=null&&goal.target!=null?<Text style={s.meta}>{goal.current} / {goal.target}</Text>:null}</View><Text style={s.pct}>{goal.progress}%</Text></View>):<View style={s.empty}><MaterialIcons name="track-changes" color="#8DA0BD" size={55}/><Text style={s.emptyTitle}>Aucun objectif synchronisé</Text><Text style={s.emptyText}>Tes objectifs apparaîtront ici dès qu’ils seront fournis par ton dashboard.</Text><Image source={require("../assets/images/dashboard-student-cameleon.svg")} style={s.cameleon} contentFit="contain"/></View>}</ScrollView><ProgressNav/></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#F6F8FC"},content:{paddingBottom:22},hero:{margin:14,minHeight:142,borderRadius:25,backgroundColor:"#168B31",padding:22,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},heroTitle:{color:"white",fontSize:29,fontWeight:"900"},heroText:{color:"white",fontSize:14,marginTop:10},tabs:{height:62,flexDirection:"row",alignItems:"center",justifyContent:"space-around",marginHorizontal:16},active:{fontWeight:"900",fontSize:16,borderBottomWidth:4,borderBottomColor:"#3FA739",paddingBottom:13},card:{marginHorizontal:14,marginBottom:11,minHeight:118,backgroundColor:"white",borderRadius:22,padding:15,flexDirection:"row",alignItems:"center",elevation:2},icon:{width:52,height:52,borderRadius:26,alignItems:"center",justifyContent:"center"},copy:{flex:1,marginHorizontal:13},title:{color:"#102352",fontWeight:"900",fontSize:16},description:{color:"#61708B",fontSize:12,marginTop:5},track:{height:8,borderRadius:4,backgroundColor:"#E6EBF3",overflow:"hidden",marginTop:12},fill:{height:"100%",backgroundColor:"#42A940"},meta:{fontSize:11,color:"#34577B",marginTop:6},pct:{fontSize:18,color:"#159A36",fontWeight:"900"},empty:{margin:16,backgroundColor:"white",borderRadius:24,padding:28,alignItems:"center"},emptyTitle:{fontSize:19,fontWeight:"900",color:"#102352",marginTop:9},emptyText:{textAlign:"center",color:"#67758B",lineHeight:20,marginTop:7},cameleon:{width:120,height:100,marginTop:10}});
