import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { Image } from "expo-image";
import { useMemo, useState } from "react";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { ProgressHeader, ProgressNav, ProgressState } from "../components/progress-layout";
import { useStudentProgress } from "../src/hooks/useStudentProgress";
const catalog=[["Premier Pas","Compléter ta première leçon",require("../assets/images/badges/premier-pas.svg")],["Persévérant","7 jours de suite",require("../assets/images/badges/perseverant.svg")],["Quiz Master","Réussir 10 quiz",require("../assets/images/badges/quiz-master.svg")],["Curieux","Regarder 5 vidéos",require("../assets/images/badges/curieux.svg")],["Champion","1000 XP gagnés",require("../assets/images/badges/champion.svg")],["Explorateur","5 matières étudiées",require("../assets/images/badges/explorateur.svg")],["Étudiant Assidu","10 leçons terminées",require("../assets/images/badges/etudiant-assidu.svg")],["Excellent","90% à un quiz",require("../assets/images/badges/excellent.svg")],["À venir…","Continue tes efforts !",require("../assets/images/badges/a-venir.svg")]] as const;
const normalize=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]/g,"");
export default function ProgressRewards(){const {dashboard,loading,error,reload}=useStudentProgress();const [filter,setFilter]=useState("Tous");const earned=useMemo(()=>new Set((dashboard?.badges??[]).map(b=>normalize(typeof b==="string"?b:String((b as Record<string,unknown>)?.name??(b as Record<string,unknown>)?.title??(b as Record<string,unknown>)?.slug??"")))),[dashboard]);if(loading||error)return <View style={s.page}><ProgressHeader back/><ProgressState loading={loading} error={error} onRetry={reload}/><ProgressNav/></View>;const rows=catalog.filter(([title])=>filter==="Tous"||(filter==="Gagnés"&&earned.has(normalize(title)))||(filter==="Verrouillés"&&!earned.has(normalize(title))));const xp=dashboard?.overview.xp??dashboard?.student.xp;return <View style={s.page}><ScrollView contentContainerStyle={s.content}><ProgressHeader back/><View style={s.hero}><View><Text style={s.heroTitle}>Badges & Récompenses</Text><Text style={s.heroSub}>Tes accomplissements</Text></View><MaterialIcons name="emoji-events" color="#FFF3A6" size={83}/></View><View style={s.filters}>{["Tous","Gagnés","Verrouillés"].map(v=><Pressable key={v} onPress={()=>setFilter(v)} style={[s.filter,filter===v&&s.filterActive]}><Text style={s.filterText}>{v}</Text></Pressable>)}</View><View style={s.grid}>{rows.map(([title,desc,source])=>{const ok=earned.has(normalize(title));return <View key={title} style={[s.badge,!ok&&s.locked]}><Image source={source} contentFit="contain" style={s.badgeImage}/><Text style={s.badgeTitle}>{title}</Text><Text style={s.badgeDesc}>{desc}</Text>{ok?<View style={s.check}><MaterialIcons name="check" color="white" size={13}/></View>:null}</View>})}</View><View style={s.rewards}><Text style={s.rewardsTitle}>Tes récompenses</Text><View style={s.rewardRow}><Reward icon="star" value={xp==null?"—":String(xp)} label="Total d’XP gagnés"/><Reward icon="military-tech" value={String(earned.size)} label="Badges obtenus"/></View></View></ScrollView><ProgressNav/></View>}
function Reward({icon,value,label}:{icon:React.ComponentProps<typeof MaterialIcons>["name"];value:string;label:string}){return <View style={s.reward}><MaterialIcons name={icon} size={39} color="#F2A600"/><View><Text style={s.rewardValue}>{value}</Text><Text style={s.rewardLabel}>{label}</Text></View></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:"#F7F8FC"},content:{paddingBottom:22},hero:{margin:14,minHeight:142,borderRadius:25,backgroundColor:"#F4A500",padding:22,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},heroTitle:{color:"white",fontSize:24,fontWeight:"900",maxWidth:240},heroSub:{color:"white",fontSize:16,marginTop:10},filters:{height:65,flexDirection:"row",alignItems:"center",justifyContent:"space-around",paddingHorizontal:12},filter:{paddingHorizontal:20,paddingVertical:10,borderRadius:20},filterActive:{borderColor:"#159A36",borderWidth:1},filterText:{color:"#14285B",fontWeight:"800"},grid:{paddingHorizontal:12,flexDirection:"row",flexWrap:"wrap",gap:8},badge:{width:"31.7%",minHeight:164,backgroundColor:"white",borderRadius:18,padding:9,alignItems:"center",justifyContent:"center",elevation:2},locked:{opacity:.55},badgeImage:{width:77,height:77},badgeTitle:{fontSize:13,fontWeight:"900",color:"#102352",textAlign:"center",marginTop:5},badgeDesc:{fontSize:10,color:"#455879",textAlign:"center",marginTop:4,lineHeight:13},check:{position:"absolute",right:7,top:7,width:20,height:20,borderRadius:10,backgroundColor:"#23A43C",alignItems:"center",justifyContent:"center"},rewards:{margin:14,backgroundColor:"#FFF4D0",borderRadius:22,padding:17},rewardsTitle:{fontSize:21,fontWeight:"900",color:"#102352"},rewardRow:{flexDirection:"row",gap:9,marginTop:14},reward:{flex:1,minHeight:80,backgroundColor:"white",borderRadius:16,padding:10,flexDirection:"row",alignItems:"center",gap:8},rewardValue:{fontSize:20,fontWeight:"900",color:"#102352"},rewardLabel:{fontSize:9,color:"#425575",maxWidth:80}});
